import { getImgPath } from './imagesPaths.js';

export const productsArr = [
  {
    id: '1',
    name: 'Crater-G',
    brand: 'NASA',
    price: 8.99,
    img: getImgPath('products', 'carterG.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'carterG1.jpg', 'product'),
      getImgPath('products', 'carterG2.jpg', 'product'),
      getImgPath('products', 'carterG3.jpg', 'product'),
      getImgPath('products', 'carterG4.jpg', 'product'),
      getImgPath('products', 'carterG5.jpg', 'product'),
      getImgPath('products', 'carterG6.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'sandals',
    size: 1,
    width: 'm',
    color: [
      {
        color: 'white',
        img: getImgPath('products', 'carterGWhite.jpg', 'product'),
      },
    ],
    style: 'comfort',
    occasion: 'casual',
    feature: 'strappy',
    material: 'manmade',
    pattern: 'solid',
    theme: 'action sports',
    accent: 'buckle',
    description: [
      'Perfect for the beach or lounging around the house, the NASA Crater-G will ensure your day is filled with lightweight comfort.',
      'SKU: #9694810',
      'Slip-on sandal with open rounded toe and open back for easy on and off.',
      'Single wide band emblazoned with NASA logo.',
      'Polyurethane upper and lining.',
      'PVC footbed and sole.',
      'Imported.',
      'Weight of footwear is based on a single item, not a pair.',
      'Measurements: Weight: 2.4 oz.',
    ],
  },
  {
    id: '2',
    name: 'Wed',
    brand: 'David Tate',
    price: 25,
    img: getImgPath('products', 'wed.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'wed1.jpg', 'product'),
      getImgPath('products', 'wed2.jpg', 'product'),
      getImgPath('products', 'wed3.jpg', 'product'),
      getImgPath('products', 'wed4.jpg', 'product'),
      getImgPath('products', 'wed5.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'heels',
    size: 1.5,
    width: 'n',
    color: 'black',
    style: 'platform',
    occasion: 'casual',
    feature: 'strappy',
    material: 'manmade',
    pattern: 'metallic',
    theme: 'winter',
    accent: 'rhinestones',
  },
  {
    id: '3',
    name: 'Asteroid-G (Little Kid)',
    brand: 'NASA',
    price: 30,
    img: getImgPath('products', 'asteroidG.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'asteroidG1.jpg', 'product'),
      getImgPath('products', 'asteroidG2.jpg', 'product'),
      getImgPath('products', 'asteroidG3.jpg', 'product'),
      getImgPath('products', 'asteroidG4.jpg', 'product'),
      getImgPath('products', 'asteroidG5.jpg', 'product'),
      getImgPath('products', 'asteroidG6.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'sandals',
    size: 2,
    width: 'm',
    color: 'black',
    style: 'slide',
    occasion: 'casual',
    feature: 'waterproof',
    material: 'manmade',
    pattern: 'reptile',
    theme: 'athletic inspired',
    accent: 'perforated',
  },
  {
    id: '4',
    name: 'Rover',
    brand: 'La Canadienne',
    price: 35,
    img: getImgPath('products', 'rover.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'rover1.jpg', 'product'),
      getImgPath('products', 'rover2.jpg', 'product'),
      getImgPath('products', 'rover3.jpg', 'product'),
      getImgPath('products', 'rover4.jpg', 'product'),
      getImgPath('products', 'rover5.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'heels',
    size: 3,
    width: 'm',
    color: 'white',
    style: 'wedges',
    occasion: 'casual',
    feature: 'arch support',
    material: 'leather',
    pattern: 'solid',
    theme: 'western',
    accent: 'studded',
  },
  {
    id: '5',
    name: 'MX Flipsider',
    brand: 'ECCO Sport',
    price: 10,
    img: getImgPath('products', 'mxFlipsider.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'mxFlipsider1.jpg', 'product'),
      getImgPath('products', 'mxFlipsider2.jpg', 'product'),
      getImgPath('products', 'mxFlipsider3.jpg', 'product'),
      getImgPath('products', 'mxFlipsider4.jpg', 'product'),
      getImgPath('products', 'mxFlipsider5.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'sandals',
    size: 3,
    width: 'm',
    color: 'beige',
    style: 'comfort',
    occasion: 'casual',
    feature: 'strappy',
    material: 'leather',
    pattern: 'solid',
    theme: 'action sports',
    accent: 'buckle',
  },
  {
    id: '6',
    name: 'Dalian',
    brand: 'Vaneli',
    price: 15,
    img: getImgPath('products', 'dalian.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'dalian1.jpg', 'product'),
      getImgPath('products', 'dalian2.jpg', 'product'),
      getImgPath('products', 'dalian3.jpg', 'product'),
      getImgPath('products', 'dalian4.jpg', 'product'),
      getImgPath('products', 'dalian5.jpg', 'product'),
      getImgPath('products', 'dalian6.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'heels',
    size: 1.5,
    width: 'n',
    color: 'black',
    style: 'platform',
    occasion: 'dress',
    feature: 'leather outsole',
    material: 'suede',
    pattern: 'solid',
    theme: 'winter',
    accent: 'rhinestones',
  },
  {
    id: '7',
    name: 'Nelina',
    brand: 'Vaneli',
    price: 35,
    img: getImgPath('products', 'nelina.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'nelina1.jpg', 'product'),
      getImgPath('products', 'nelina2.jpg', 'product'),
      getImgPath('products', 'nelina3.jpg', 'product'),
      getImgPath('products', 'nelina4.jpg', 'product'),
      getImgPath('products', 'nelina5.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'sandals',
    size: 2,
    width: 'n',
    color: 'white',
    style: 'slide',
    occasion: 'casual',
    feature: 'strappy',
    material: 'fabric',
    pattern: 'solid',
    theme: 'athletic inspired',
    accent: 'perforated',
  },
  {
    id: '8',
    name: 'Shandra',
    brand: 'Easy Spirit',
    price: 28,
    img: getImgPath('products', 'shandra.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'shandra1.jpg', 'product'),
      getImgPath('products', 'shandra2.jpg', 'product'),
      getImgPath('products', 'shandra3.jpg', 'product'),
      getImgPath('products', 'shandra4.jpg', 'product'),
      getImgPath('products', 'shandra5.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'heels',
    size: 3,
    width: 'm',
    color: 'beige',
    style: 'wedges',
    occasion: 'dress',
    feature: 'arch support',
    material: 'suede',
    pattern: 'solid',
    theme: 'western',
    accent: 'studded',
  },
];
