import { getImgPath } from './imagesPaths.js';

export const productsArr = [
  {
    id: '1',
    name: 'Crater-G',
    brand: 'NASA',
    price: 8.99,
    img: getImgPath('products', 'carterG.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'carterG1.jpg', 'product'),
      getImgPath('products', 'carterG2.jpg', 'product'),
      getImgPath('products', 'carterG3.jpg', 'product'),
      getImgPath('products', 'carterG4.jpg', 'product'),
      getImgPath('products', 'carterG5.jpg', 'product'),
      getImgPath('products', 'carterG6.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'sandals',
    size: 1,
    width: 'm',
    color: [
      {
        color: 'white',
        img: getImgPath('products', 'carterGWhite.jpg', 'product'),
      },
    ],
    style: 'comfort',
    occasion: 'casual',
    feature: 'strappy',
    material: 'manmade',
    pattern: 'solid',
    theme: 'action sports',
    accent: 'buckle',
    description: [
      'Perfect for the beach or lounging around the house, the NASA Crater-G will ensure your day is filled with lightweight comfort.',
      'SKU: #9694810',
      'Slip-on sandal with open rounded toe and open back for easy on and off.',
      'Single wide band emblazoned with NASA logo.',
      'Polyurethane upper and lining.',
      'PVC footbed and sole.',
      'Imported.',
      'Weight of footwear is based on a single item, not a pair.',
      'Measurements: Weight: 2.4 oz.',
    ],
  },
  {
    id: '2',
    name: 'Wed',
    brand: 'David Tate',
    price: 25,
    img: getImgPath('products', 'wed.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'wed1.jpg', 'product'),
      getImgPath('products', 'wed2.jpg', 'product'),
      getImgPath('products', 'wed3.jpg', 'product'),
      getImgPath('products', 'wed4.jpg', 'product'),
      getImgPath('products', 'wed5.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'heels',
    size: 1.5,
    width: 'n',
    color: [
      {
        color: 'black',
        img: getImgPath('products', 'wedBlack.jpg', 'product'),
      },
    ],
    style: 'platform',
    occasion: 'casual',
    feature: 'strappy',
    material: 'manmade',
    pattern: 'metallic',
    theme: 'winter',
    accent: 'rhinestones',
    description: [
      'Twirl on the dance floor by slaying in the David Tate® Wed sandals.',
      'SKU: #9675920',
      'Man-made upper and lining for added comfort.',
      'Open round toe.',
      'Sky-high block heels.',
      'Buckle closure on the ankle strap.',
      'Man-made outsole.',
      'Imported.',
      'Product measurements were taken using size 6, width M (B). Please note that measurements may vary by size.',
      'Weight of footwear is based on a single item, not a pair.',
      'Measurements: Heel Height: 2 1⁄2 in Weight: 7 oz',
    ],
  },
  {
    id: '3',
    name: 'Asteroid-G (Little Kid)',
    brand: 'NASA',
    price: 30,
    img: getImgPath('products', 'asteroidG.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'asteroidG1.jpg', 'product'),
      getImgPath('products', 'asteroidG2.jpg', 'product'),
      getImgPath('products', 'asteroidG3.jpg', 'product'),
      getImgPath('products', 'asteroidG4.jpg', 'product'),
      getImgPath('products', 'asteroidG5.jpg', 'product'),
      getImgPath('products', 'asteroidG6.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'sandals',
    size: 2,
    width: 'm',
    color: [
      {
        color: 'black',
        img: getImgPath('products', 'asteroidGBlack.jpg', 'product'),
      },
    ],
    style: 'slide',
    occasion: 'casual',
    feature: 'waterproof',
    material: 'manmade',
    pattern: 'reptile',
    theme: 'athletic inspired',
    accent: 'perforated',
    description: [
      'Take your poolside style to new heights in the NASA Asteroid-G sandals.',
      'SKU: #9694811',
      'Slip on design in a round, open toe silhouette.',
      'Single band upper is lightweight and durable.',
      'Quick dry soft and comfortable footbed.',
      'One-piece preference molded EVA slide provides cushioning and impact protection.',
      'Anti-skid textured bottom for added floor friction.',
      'Graphic screen print on strap.',
      'PU upper.',
      'Textile lining and insole.',
      'PVC outsole.',
      'Imported.',
      'Weight of footwear is based on a single item, not a pair.',
    ],
  },
  {
    id: '4',
    name: 'Rover',
    brand: 'La Canadienne',
    price: 35,
    img: getImgPath('products', 'rover.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'rover1.jpg', 'product'),
      getImgPath('products', 'rover2.jpg', 'product'),
      getImgPath('products', 'rover3.jpg', 'product'),
      getImgPath('products', 'rover4.jpg', 'product'),
      getImgPath('products', 'rover5.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'heels',
    size: 3,
    width: 'm',
    color: [
      {
        color: 'white',
        img: getImgPath('products', 'roverWhite.jpg', 'product'),
      },
    ],
    style: 'wedges',
    occasion: 'casual',
    feature: 'arch support',
    material: 'leather',
    pattern: 'solid',
    theme: 'western',
    accent: 'studded',
    description: [
      'Boasting a retro-inspired style with a modish touch, the La Canadienne® Rover sandals are sure to become your forever favorite.',
      'SKU: #9839614',
      'Leather upper with puffy quilted details.',
      'Leather lining and insole.',
      'Adjustable hook-and-loop closure on the ankle strap.',
      'Open square toe silhouette.',
      'Chunky block heel.',
      'Durable leather outsole.',
      'Made in Italy.',
      "Product measurements were taken using size EU 40 (US Women's 9-9.5), width M (B). Please note that measurements may vary by size.",
      'Measurements: Heel Height: 2 in Weight: 9 oz',
    ],
  },
  {
    id: '5',
    name: 'MX Flipsider',
    brand: 'ECCO Sport',
    price: 10,
    img: getImgPath('products', 'mxFlipsider.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'mxFlipsider1.jpg', 'product'),
      getImgPath('products', 'mxFlipsider2.jpg', 'product'),
      getImgPath('products', 'mxFlipsider3.jpg', 'product'),
      getImgPath('products', 'mxFlipsider4.jpg', 'product'),
      getImgPath('products', 'mxFlipsider5.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'sandals',
    size: 3,
    width: 'm',
    color: [
      {
        color: 'vetiver',
        img: getImgPath('products', 'mxFlipsiderVetiver.jpg', 'product'),
      },
    ],
    style: 'comfort',
    occasion: 'casual',
    feature: 'strappy',
    material: 'leather',
    pattern: 'solid',
    theme: 'action sports',
    accent: 'buckle',
    description: [
      'A vigorous update on the classic style, the ECCO® Sport MX Flipsider Sandals are designed to offer you a relaxed feel, flexibility, and durability. Wear it on your adventure trips, on the beach, or the poolside!',
      'SKU: #9598840',
      'Crafted from robust materials which will not be damaged in fresh and salt water.',
      'Casual flip flops with full-grain leather upper.',
      'Leather lining.',
      'Padded synthetic insole.',
      'ECCO FLUIDFORM™ Direct Comfort Technology offers high rebound and cushioning.',
      'Low-to-the-ground sole follows the natural foot shape for enhanced stability and support.',
      'Slip-on construction.',
      'Open toe design.',
      'Rugged, motocross-inspired synthetic outsole offers superior grip and traction.',
      'Imported.',
      "Product measurements were taken using size EU 43 (US Men's 9-9.5, Women's 12-12.5), width Medium. Please note that measurements may vary by size.",
      'Weight of footwear is based on a single item, not a pair.',
      'Measurements: Weight: 10 oz',
    ],
  },
  {
    id: '6',
    name: 'Dalian',
    brand: 'Vaneli',
    price: 15,
    img: getImgPath('products', 'dalian.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'dalian1.jpg', 'product'),
      getImgPath('products', 'dalian2.jpg', 'product'),
      getImgPath('products', 'dalian3.jpg', 'product'),
      getImgPath('products', 'dalian4.jpg', 'product'),
      getImgPath('products', 'dalian5.jpg', 'product'),
      getImgPath('products', 'dalian6.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'heels',
    size: 1.5,
    width: 'n',
    color: [
      {
        color: 'black',
        img: getImgPath('products', 'dalianBlack.jpg', 'product'),
      },
    ],
    style: 'platform',
    occasion: 'dress',
    feature: 'leather outsole',
    material: 'suede',
    pattern: 'solid',
    theme: 'winter',
    accent: 'rhinestones',
    description: [
      'Unfurl the magic of versatile street chic style wearing Vaneli® Dalian Pumps. The slip-on footwear features perforated suede upper construction with synthetic rubber lining and insole.',
      'SKU: #9939900',
      'Wedge heels.',
      'Rubber outsole.',
      'Imported.',
    ],
  },
  {
    id: '7',
    name: 'Nelina',
    brand: 'Vaneli',
    price: 35,
    img: getImgPath('products', 'nelina.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'nelina1.jpg', 'product'),
      getImgPath('products', 'nelina2.jpg', 'product'),
      getImgPath('products', 'nelina3.jpg', 'product'),
      getImgPath('products', 'nelina4.jpg', 'product'),
      getImgPath('products', 'nelina5.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'sandals',
    size: 2,
    width: 'n',
    color: [
      {
        color: 'white',
        img: getImgPath('products', 'nelinaWhite.jpg', 'product'),
      },
    ],
    style: 'slide',
    occasion: 'casual',
    feature: 'strappy',
    material: 'fabric',
    pattern: 'solid',
    theme: 'athletic inspired',
    accent: 'perforated',
    description: [
      'Coming in neutral shades, the Vaneli® Nelina Sandals are a versatile pair of shoes that impress with a stud-embellished strappy leather upper coupled with a soft synthetic lining and a padded leather insole for unparalleled comfort and support.',
      'SKU: #9939955',
      'Adjustable buckled strap closure.',
      'Rubber outsole.',
      'Imported.',
      'Product measurements were taken using size 7, width M (B). Please note that measurements may vary by size.',
      'Measurements: Weight: 1 lb 8 oz',
    ],
  },
  {
    id: '8',
    name: 'Shandra',
    brand: 'Easy Spirit',
    price: 28,
    img: getImgPath('products', 'shandra.jpg', 'product'),
    imgSet: [
      getImgPath('products', 'shandra1.jpg', 'product'),
      getImgPath('products', 'shandra2.jpg', 'product'),
      getImgPath('products', 'shandra3.jpg', 'product'),
      getImgPath('products', 'shandra4.jpg', 'product'),
      getImgPath('products', 'shandra5.jpg', 'product'),
    ],
    category: 'shoes',
    subcategory: 'women',
    subsubcategory: 'heels',
    size: 3,
    width: 'm',
    color: [
      {
        color: 'beige',
        img: getImgPath('products', 'nelinaWhite.jpg', 'product'),
      },
    ],
    style: 'wedges',
    occasion: 'dress',
    feature: 'arch support',
    material: 'suede',
    pattern: 'solid',
    theme: 'western',
    accent: 'studded',
    description: [
      'Add both style and functionality to your look by complementing it with the Easy Spirit® Shandra Sandals crafted with a suede & textile upper, textile lining, and cushioned foam footbed. The sandals feature an open round toe, cross-strap detailing, wedge heel for better arch support and an ankle strap & adjustable buckle closure for a secured fit.',
      'SKU: #9966128',
      'Durable synthetic rubber oustole.',
      'Imported.',
      'Product measurements were taken using size 5, width M (B). Please note that measurements may vary by size.',
      'Measurements: Heel Height: 2 5⁄14 in Weight: 1 lb Platform Height: 3⁄5 in',
    ],
  },
];
