export function leftFilter() {
  return `
		
        <li>
          <h3></h3>
          <ul></ul>
        </li>
        <li>
          <h3></h3>
          <ul></ul>
        </li>
        <li>
          <h3></h3>
          <ul></ul>
        </li>
        <li>
          <h3></h3>
          <ul></ul>
        </li>
        <li>
          <h3></h3>
          <ul></ul>
        </li>
        <li>
          <h3></h3>
          <ul></ul>
        </li>
        <li>
          <h3></h3>
          <ul></ul>
        </li>
        <li>
          <h3></h3>
          <ul></ul>
        </li>
        <li>
          <h3></h3>
          <ul></ul>
        </li>
        <li>
          <h3></h3>
          <ul></ul>
        </li>
        <li>
          <h3></h3>
          <ul></ul>
        </li>
        <li>
          <h3></h3>
          <ul></ul>
        </li>
        <li>
          <h3></h3>
          <ul></ul>
        </li>
      </ul>
    </div>
	`;
}
